name: mentoview backend test 06

on:
  workflow_dispatch
#  push:
#    branches:
#      - test

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      # env:
        # GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: build/libs

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: be-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
    - name: Update application image version for ArgoCD
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.G_USER }}/${{ secrets.G_REPOSITORY }}
        ref: main
        token: ${{ secrets.G_TOKEN }}
    
    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_ECR_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:be-[a-zA-Z0-9]*%image: ${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_ECR_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:be-${{ github.sha }}%" ./BE/mv-be-manifest.yaml
    
    - name: Commit and push changes
      run: |
        git config --local user.email "${{ secrets.G_USER_EMAIL }}"
        git config --local user.name "${{ secrets.G_USER_NAME }}"
        git add .
        git commit -m "Update application image version for ArgoCD"
        git push
